// Code generated by tack. DO NOT EDIT.

package prod

import (
	"case-01/src/state"
	"context"
	"fmt"

	"testing"
)

func NewProdState(ctx context.Context) (state.State, func(), error) {
	var cleanups []func()
	cleanup := func() {
		for i := len(cleanups) - 1; i >= 0; i-- {
			cleanups[i]()
		}
	}

	// provide Store() type of *state.Store
	store, storeCleanup, err := ProvideStore(ctx)
	if err != nil {
		cleanup()
		return nil, nil, fmt.Errorf("ProvideStore: %w", err)
	}
	if storeCleanup != nil {
		cleanups = append(cleanups, storeCleanup)
	}

	return &prodState{
		store: store,
	}, cleanup, nil
}

var _ state.State = (*prodState)(nil)

type prodState struct {
	store *state.Store
}

// Store implements [state.State].
func (i *prodState) Store() *state.Store {
	return i.store
}

type ProdTestState struct {
	_     struct{} // enforce keyed fields; see writeStructDecl
	Store *state.Store
}

func NewProdTestState(t testing.TB, s ProdTestState) state.State {
	t.Helper()
	if s.Store == nil {
		t.Fatalf("%s.%s not set", "ProdTestState", "Store")
	}
	return &prodState{
		store: s.Store,
	}
}
