// Code generated by tack. DO NOT EDIT.

package staging

import (
	provider02 "case-01/src/provider-02"
	"case-01/src/state"
	"context"
	"fmt"

	"testing"
)

func NewStagingState(ctx context.Context) (state.State, func(), error) {
	var cleanups []func()
	cleanup := func() {
		for i := len(cleanups) - 1; i >= 0; i-- {
			cleanups[i]()
		}
	}

	// provide Store() type of *state.Store
	store, storeCleanup, err := provider02.ProvideStore(ctx)
	if err != nil {
		cleanup()
		return nil, nil, fmt.Errorf("ProvideStore: %w", err)
	}
	if storeCleanup != nil {
		cleanups = append(cleanups, storeCleanup)
	}

	return &stagingState{
		store: store,
	}, cleanup, nil
}

var _ state.State = (*stagingState)(nil)

type stagingState struct {
	store *state.Store
}

// Store implements [state.State].
func (i *stagingState) Store() *state.Store {
	return i.store
}

type StagingTestState struct {
	_     struct{} // enforce keyed fields; see writeStructDecl
	Store *state.Store
}

func NewStagingTestState(t testing.TB, s StagingTestState) state.State {
	t.Helper()
	if s.Store == nil {
		t.Fatalf("%s.%s not set", "StagingTestState", "Store")
	}
	return &stagingState{
		store: s.Store,
	}
}
