// Code generated by tack. DO NOT EDIT.

package iface

import (
	"case-01/src/a"
	"case-01/src/b"
	"case-01/src/c"
	"case-01/src/d"
	provider01 "case-01/src/provider-01"
	provider02 "case-01/src/provider-02"
	"context"
	"fmt"

	"testing"
)

func NewAppIface(ctx context.Context) (Iface, func(), error) {
	var cleanups []func()
	cleanup := func() {
		for i := len(cleanups) - 1; i >= 0; i-- {
			cleanups[i]()
		}
	}

	// provide MethodA() type of a.IA
	methodA, methodACleanup, err := provider01.ProvideA(ctx)
	if err != nil {
		cleanup()
		return nil, nil, fmt.Errorf("ProvideA: %w", err)
	}
	if methodACleanup != nil {
		cleanups = append(cleanups, methodACleanup)
	}

	// provide B() type of b.IB
	b, bCleanup, err := provider01.ProvideXXX(ctx)
	if err != nil {
		cleanup()
		return nil, nil, fmt.Errorf("ProvideXXX: %w", err)
	}
	if bCleanup != nil {
		cleanups = append(cleanups, bCleanup)
	}

	// provide Foo() type of *c.C
	foo, fooCleanup, err := ProvideC(ctx)
	if err != nil {
		cleanup()
		return nil, nil, fmt.Errorf("ProvideC: %w", err)
	}
	if fooCleanup != nil {
		cleanups = append(cleanups, fooCleanup)
	}

	// provide BarClient() type of *d.D
	barClient, barClientCleanup, err := provider02.ProvideYYY(ctx)
	if err != nil {
		cleanup()
		return nil, nil, fmt.Errorf("ProvideYYY: %w", err)
	}
	if barClientCleanup != nil {
		cleanups = append(cleanups, barClientCleanup)
	}

	return &appIface{
		methodA:   methodA,
		b:         b,
		foo:       foo,
		barClient: barClient,
	}, cleanup, nil
}

var _ Iface = (*appIface)(nil)

type appIface struct {
	methodA   a.IA
	b         b.IB
	foo       *c.C
	barClient *d.D
}

// MethodA implements [Iface].
func (i *appIface) MethodA() a.IA {
	return i.methodA
}

// B implements [Iface].
func (i *appIface) B() b.IB {
	return i.b
}

// Foo implements [Iface].
func (i *appIface) Foo() *c.C {
	return i.foo
}

// BarClient implements [Iface].
func (i *appIface) BarClient() *d.D {
	return i.barClient
}

type AppTestIface struct {
	_         struct{} // enforce keyed fields; see writeStructDecl
	MethodA   a.IA
	B         b.IB
	Foo       *c.C
	BarClient *d.D
}

func NewAppTestIface(t testing.TB, s AppTestIface) Iface {
	t.Helper()
	if s.MethodA == nil {
		t.Fatalf("%s.%s not set", "AppTestIface", "MethodA")
	}
	if s.B == nil {
		t.Fatalf("%s.%s not set", "AppTestIface", "B")
	}
	if s.Foo == nil {
		t.Fatalf("%s.%s not set", "AppTestIface", "Foo")
	}
	if s.BarClient == nil {
		t.Fatalf("%s.%s not set", "AppTestIface", "BarClient")
	}
	return &appIface{
		methodA:   s.MethodA,
		b:         s.B,
		foo:       s.Foo,
		barClient: s.BarClient,
	}
}
